---
- name: chrony | Add the OS specific variables
  include_vars: "ubuntu.yml"
  # designujes roli pro jeden OS (nemas tam specificke vars pro rhel nebo centos) 
  # zjednodus to, misto include vars ubuntu.yml z vars slozky toto vypust a dej do vars slozky jen "main.yml", kde to vydefinujes
  # ansible si to tak natahne by default a nemusis resit

- name: chrony | Installation
  include_tasks: "ubuntu.yml"
  
  # fajn ze to je oddelene pres include tasks, ale dalsi veci si neoddelil why?
  # ten template a ta service by mohla byt v chrony-setup.yml a misto ubuntu.yml by si to mohl pojmenovat jako install.yml (protoze opet nemas OS-specific
  # instalacni postupy, delame jen na ubuntu

- name: chrony | Copy the chrony.conf template file
  template:
    src: chrony.conf.j2
    dest: "{{ chrony_config_location }}"
  notify:
    - restart chrony
    
  # je dobry kvuli debugu a prehlednosti pojmenovat tasky i cislem od 1. a dale
  # hodi se to kdyz poustis ansible, ze hnedka vidis roli + cislo, kde to dela problem

- name: chrony | start and enable chrony service
  service:
    name: "{{ chrony_service_name }}"
    state: "{{ chrony_service_state }}"
    enabled: "{{ chrony_service_enabled }}"

  # daemon reload neni treba? nebo jo? rekni proc
